# Generated by Django 6.0.2 on 2026-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.CharField(blank=True, max_length=64, null=True)),
                ('multiplier', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('volatility', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
